#pragma once
#include "lvgl.h"

/* Brands */
#include "youtube_brands_solid_full_a8_32.h"
#include "reddit_brands_solid_full_a8_32.h"
#include "amazon_brands_solid_full_a8_32.h"
#include "discord_brands_solid_full_a8_32.h"
#include "meta_brands_solid_full_a8_32.h"
#include "xbox_brands_solid_full_a8_32.h"
#include "google_pay_brands_solid_full_a8_32.h"
#include "cash_app_brands_solid_full_a8_32.h"
#include "twitch_brands_solid_full_a8_32.h"
#include "itunes_note_brands_solid_full_a8_32.h"

/* Weather */
#include "sun_regular_full_a8_32.h"
#include "cloud_sun_solid_full_a8_32.h"
#include "cloud_rain_solid_full_a8_32.h"
#include "cloud_showers_heavy_solid_full_a8_32.h"
#include "cloud_bolt_solid_full_a8_32.h"
#include "cloud_solid_full_a8_32.h"
#include "cloud_regular_full_a8_32.h"
#include "cloud_moon_solid_full_a8_32.h"
#include "cloud_moon_rain_solid_full_a8_32.h"

/* Utility */
#include "comments_regular_full_a8_32.h"
#include "voicemail_solid_full_a8_32.h"
#include "desktop_solid_full_a8_32.h"
#include "floppy_disk_regular_full_a8_32.h"
#include "clock_regular_full_a8_32.h"
#include "calendar_solid_full_a8_32.h"
#include "calendar_regular_full_a8_32.h"
#include "alarm_clock_solid_full_a8_32.h"
#include "headphones_regular_full_a8_32.h"
#include "heart_pulse_solid_full_a8_32.h"
#include "f_solid_full_a8_32.h"
#include "message_regular_full_a8_32.h"
#include "envelope_regular_full_a8_32.h"
#include "gear_solid_full_a8_32.h"
#include "mobile_solid_full_a8_32.h"